# Name of your application. Used to uniquely configure containers.
service: cable_car

# Name of the container image in ECR
image: rails_8/cable_car

# Deploy to these servers (replace with your EC2 public IP).
servers:
  web:
    - 44.192.49.202

# SSL via Let's Encrypt (free, auto-renewed by kamal-proxy).
proxy:
  ssl: true
  host: cablecar.click

# AWS ECR registry credentials.
registry:
  server: 029212082144.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

# Environment variables for containers.
env:
  secret:
    - RAILS_MASTER_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    AWS_REGION: us-east-1
    AWS_BUCKET: cable-car-assets
    CDN_HOST: dy3w5ttukbq3c.cloudfront.net

# Aliases for common commands.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Persistent storage for SQLite and Active Storage local files.
volumes:
  - "cable_car_storage:/rails/storage"

# Bridge assets between versions.
asset_path: /rails/public/assets

# Build for amd64 (EC2).
builder:
  arch: amd64

ssh:
  user: ubuntu
  keys:
    - ~/Documents/Personal Projects/rails_8/cable_car_key.pem

# Use accessory services (secrets come from .kamal/secrets).
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     # Change to 3306 to expose port to the world instead of just local network.
#     port: "127.0.0.1:3306:3306"
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data

